### PR TITLE
upgrade Django to v4.2.16 (iss. #503)

### LINKED ISSUE #503: Upgrade Django version to 4.2
Django 3.2 recently end EOL, so we should upgrade the backend to Django 4.2. This would include upgrading other related dependencies such as channels and other django-* packages.  

Django Channels 4.1.0 supports a new "reason" parameter to the close method which could allow passing additional information into the frontend to make some error messaging more specific for the 4404 and other similar errors passed into `useWebSockets`.

### PR DESCRIPTION
**Pull request by lsloan**
Resolves #503.

Very simple, small change, but requires a lot of testing to be sure it doesn't cause problems with the application.

* [x] Install Twilio credentials locally to test those features before deploying this change to the dev/test server
* [x] Upgrade other packages in `requirements.txt`
* [ ] (Opt) Check vulnerability report

### CODE REVIEW

**Comment by lsloan** [comment]
Almost ready.  I need to finish upgrading the packages in `requirements.txt`.

**Comment by lsloan** [comment]
As suggested by @jonespm, after upgrading Django to 4.2.16, I've upgraded all other packages.  After this upgrade, the Django tests (`./manage.py test -v2` with environment variables set for `TWILIO_*`, `OIDC_*`, & `ZOOM_*`) were all successful.  Most of the packages are for web application features.  However, the `twilio` package is specific to that service.  Although the Twilio tests passed, I question whether the upgrade `7.16.4` → `9.3.3` might introduce incompatibilities.

**Comment by lsloan** [comment]
@zqian, I've requested a review from you.  I know @jonespm is busy with other projects, so I didn't know whether to request a review from him.  If you think it's appropriate, you can add other reviewers to this PR.

In the meantime, I'm considering the project's vulnerability report to decide whether there is anything in it that needs action.

**Review by zqian — APPROVED** [review]
I have tested basic functions of ROHQ, including the Twilio messaging. Everything looks fine, and there is no errors in log.

**Pull request merged**
