### PR TITLE
Update turn alert and meeting card on queue attendee page (#231, #232)

### PR DESCRIPTION
**Pull request by ssciolla**
This PR makes requested changes to `queue.tsx`, specifically to the turn alert at the top of the page and the meeting card. The PR aims to resolve both issues #231 and #232.

### CODE REVIEW

**Review by mfldavidson — APPROVED** [review]
Based on the demo Sam showed me today I approve this PR--it's looking great!

**Comment by jlost** [comment]
The code looks good, and so does the UI. I had one very small quibble with the presentation:
image
Here, "In Person" is hard to distinguish from "A Host ..." owing to the formatting being tweaked. Maybe the "A Host ..." blurb could be in parentheses or italics or separated by a line break.

**Review by jlost — APPROVED** [review]

**Comment by ssciolla** [comment]
> Here, "In Person" is hard to distinguish from "A Host ..." owing to the formatting being tweaked. Maybe the "A Host ..." blurb could be in parentheses or italics or separated by a line break.

I agree, I was thinking that was out of scope, but I'll see if parentheses or some other styling makes it look better.

**Comment by ssciolla** [comment]
K, @jlost, I added parentheses (and removed a couple custom CSS classes in favor of using Bootstrap margin utilities). See below. I'm going to merge now, thanks for the review.
Screen Shot 2020-12-07 at 11 23 10 AM

**Pull request merged**
